openai:
  apikey: "Your Open AI Key"

pinecone:
  apikey: "Your Pinecone API Key"
  index_name: "Your Pinecone Index Name Where the embeddings are stored"
  environment: "The Envoirnment of the Index"

data_dir:
  path: "./data"
